const CATS=['Pre Clean Classroom','Pre Clean OJT','Passivation Classroom','Passivation OJT','Detailed Cleaning Classroom','Detailed Cleaning OJT','Sampling Classroom','Sampling OJT','Packaging Classroom','Packaging OJT','Documentation','Disassembly/Reassembly Classroom','Disassembly/Reassembly OJT','Hydrostatic Testing','Pneumatic Testing','Cryogenic Testing'];
const $=s=>document.querySelector(s), pad=n=>String(n).padStart(2,'0');
const key=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const parse=s=>{const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)};
const monday=d=>{d=new Date(d);const n=d.getDay();d.setDate(d.getDate()+(n===0?-6:1-n));d.setHours(0,0,0,0);return d};
const fmt=n=>n?Number(n).toFixed(1):'';
let entries=[], selected=monday(new Date()), pendingPdf=false;
$('#date').value=key(new Date()); $('#category').innerHTML='<option value="">Choose category</option>'+CATS.map(x=>`<option>${x}</option>`).join('');
function dbOpen(){return new Promise((ok,no)=>{const q=indexedDB.open('LTA_OJT_Tracker',2);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains('entries'))q.result.createObjectStore('entries',{keyPath:'id',autoIncrement:true})};q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error)})}
async function all(){const d=await dbOpen();return new Promise((ok,no)=>{const q=d.transaction('entries').objectStore('entries').getAll();q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error)})}
async function add(v){const d=await dbOpen();return new Promise((ok,no)=>{const q=d.transaction('entries','readwrite').objectStore('entries').add(v);q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error)})}
async function del(id){const d=await dbOpen();return new Promise((ok,no)=>{const q=d.transaction('entries','readwrite').objectStore('entries').delete(id);q.onsuccess=ok;q.onerror=()=>no(q.error)})}
function range(){const end=new Date(selected);end.setDate(end.getDate()+7);return [selected,end]}
function weekEntries(){const [a,b]=range();return entries.filter(e=>{const d=parse(e.date);return d>=a&&d<b})}
function matrix(){const m=CATS.map(()=>Array(7).fill(0));for(const e of weekEntries()){const ci=CATS.indexOf(e.category);if(ci<0)continue;const d=parse(e.date),di=d.getDay()===0?6:d.getDay()-1;m[ci][di]+=Number(e.hours)}return m}
function render(){const now=key(new Date()),cur=monday(new Date()),curEnd=new Date(cur);curEnd.setDate(curEnd.getDate()+7);$('#today').textContent=entries.filter(e=>e.date===now).reduce((s,e)=>s+Number(e.hours),0).toFixed(1);$('#week').textContent=entries.filter(e=>{const d=parse(e.date);return d>=cur&&d<curEnd}).reduce((s,e)=>s+Number(e.hours),0).toFixed(1);$('#all').textContent=entries.reduce((s,e)=>s+Number(e.hours),0).toFixed(1);const end=new Date(selected);end.setDate(end.getDate()+6);$('#weekLabel').textContent=`${selected.toLocaleDateString(undefined,{month:'short',day:'numeric'})} – ${end.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}`;const m=matrix();$('#summary').innerHTML=m.map((v,i)=>({v,i,t:v.reduce((a,b)=>a+b,0)})).filter(x=>x.t).map(x=>`<tr><td>${CATS[x.i]}</td>${x.v.map(fmt).map(v=>`<td>${v}</td>`).join('')}<td><b>${fmt(x.t)}</b></td></tr>`).join('')||'<tr><td colspan="9" class="muted">No hours logged for this week.</td></tr>';const recent=[...entries].sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id).slice(0,30);$('#entries').innerHTML=recent.map(e=>`<div class="entry"><div><b>${e.category}</b><br><small>${parse(e.date).toLocaleDateString()} · ${fmt(e.hours)} hours</small></div><button class="danger" data-id="${e.id}">Delete</button></div>`).join('')||'No entries yet.';document.querySelectorAll('[data-id]').forEach(b=>b.onclick=async()=>{if(confirm('Delete this entry?')){await del(Number(b.dataset.id));entries=await all();render()}})}
$('#form').onsubmit=async e=>{e.preventDefault();const v={date:$('#date').value,category:$('#category').value,hours:Number($('#hours').value),createdAt:Date.now()};v.id=await add(v);entries.push(v);$('#hours').value='';$('#status').textContent='Entry saved on this device.';render()};
$('#prev').onclick=()=>{selected.setDate(selected.getDate()-7);render()};$('#next').onclick=()=>{selected.setDate(selected.getDate()+7);render()};
function download(bytes,name,type){const b=new Blob([bytes],{type}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
$('#csv').onclick=()=>{const m=matrix(),rows=[['Category','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday','Total']];m.forEach((v,i)=>{const t=v.reduce((a,b)=>a+b,0);if(t)rows.push([CATS[i],...v,t])});download(rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(',')).join('\n'),`OJT_${key(selected)}.csv`,'text/csv')};
$('#backup').onclick=()=>download(JSON.stringify({version:1,exportedAt:new Date().toISOString(),entries},null,2),`OJT_Backup_${key(new Date())}.json`,'application/json');
$('#restore').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!Array.isArray(data.entries))throw Error();if(!confirm('Replace current entries with this backup?'))return;const d=await dbOpen(),tx=d.transaction('entries','readwrite'),s=tx.objectStore('entries');s.clear();for(const x of data.entries)s.add({date:x.date,category:x.category,hours:Number(x.hours),createdAt:x.createdAt||Date.now()});await new Promise((ok,no)=>{tx.oncomplete=ok;tx.onerror=no});entries=await all();render();$('#status').textContent='Backup restored.'}catch{$('#status').textContent='That backup could not be restored.'}e.target.value=''};
async function generate(){const name=localStorage.getItem('ojtEmployee')||'';if(!name){pendingPdf=true;$('#employee').value='';$('#profile').showModal();return}const button=$('#pdf');button.disabled=true;button.textContent='Generating…';try{const {PDFDocument,rgb,StandardFonts}=PDFLib;const response=await fetch('template.pdf');if(!response.ok)throw new Error(`Template unavailable (${response.status})`);const src=await response.arrayBuffer(),doc=await PDFDocument.load(src),page=doc.getPage(0),font=await doc.embedFont(StandardFonts.Helvetica),bold=await doc.embedFont(StandardFonts.HelveticaBold),ink=rgb(.05,.05,.05);const put=(txt,x,y,size=8,f=font)=>page.drawText(String(txt),{x,y,size,font:f,color:ink});const center=(txt,cx,y,size=8,f=font)=>put(txt,cx-f.widthOfTextAtSize(String(txt),size)/2,y,size,f);put(name,214,454,9,bold);const sun=new Date(selected);sun.setDate(sun.getDate()+6);put(`${pad(sun.getMonth()+1)}/${pad(sun.getDate())}/${sun.getFullYear()}`,214,437,9,bold);const m=matrix(),xs=[160,194,228,262,296,330,365,398,433,467,506,554,602,641,675,710],ys=[352.0,333.1,314.2,295.3,276.4,257.5,238.6];m.forEach((vals,ci)=>vals.forEach((v,di)=>{if(v)center(fmt(v),xs[ci],ys[di],8,bold)}));m.forEach((vals,ci)=>{const t=vals.reduce((a,b)=>a+b,0);if(t)center(fmt(t),xs[ci],222,8,bold)});const total=m.flat().reduce((a,b)=>a+b,0);center(fmt(total),117,204,9,bold);const bytes=await doc.save(),filename=`LTA_OJT_${key(selected)}_to_${key(sun)}.pdf`,blob=new Blob([bytes],{type:'application/pdf'}),url=URL.createObjectURL(blob),ready=$('#pdfReady');if(ready.dataset.url)URL.revokeObjectURL(ready.dataset.url);ready.href=url;ready.download=filename;ready.dataset.url=url;ready.style.display='block';$('#status').textContent='PDF created. Tap “PDF ready — open it” if the Share sheet does not appear.';try{if(typeof File!=='undefined'&&navigator.share){const file=new File([blob],filename,{type:'application/pdf'});if(!navigator.canShare||navigator.canShare({files:[file]}))await navigator.share({title:'Completed LTA OJT Form',files:[file]})}}catch(shareError){if(shareError.name!=='AbortError')console.warn('Share unavailable; open button remains available.',shareError)}}catch(err){console.error(err);$('#status').textContent=`PDF error: ${err&&err.message?err.message:'unknown error'}.` }finally{button.disabled=false;button.textContent='Generate OJT Form PDF'}}
$('#pdf').onclick=generate;$('#saveProfile').onclick=()=>{localStorage.setItem('ojtEmployee',$('#employee').value.trim());if(pendingPdf){pendingPdf=false;setTimeout(generate,100)}};
all().then(x=>{entries=x;$('#status').textContent=`Automatic saving enabled · ${x.length} saved ${x.length===1?'entry':'entries'} loaded.`;render()}).catch(()=>{$('#status').textContent='Device storage is unavailable.'});if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
